#pragma once

#include "CrashEngine/math/vecs.hpp"

namespace crashengine::math {
    template<typename T>
    class Vec4 : public Vec<T, 4> {
        public:
            Vec4();
            Vec4(const std::array<T, 4> &content);
            Vec4(const T &x, const T &y, const T &z, const T &w);

            T x() const;
            T y() const;
            T z() const;
            T w() const;
            std::array<T, 2> xy() const;
            std::array<T, 2> xz() const;
            std::array<T, 2> xw() const;
            std::array<T, 2> yz() const;
            std::array<T, 2> yw() const;
            std::array<T, 2> zw() const;
            std::array<T, 2> yx() const;
            std::array<T, 2> zx() const;
            std::array<T, 2> wx() const;
            std::array<T, 2> zy() const;
            std::array<T, 2> wy() const;
            std::array<T, 2> wz() const;
            std::array<T, 3> xyz() const;
            std::array<T, 3> xyw() const;
            std::array<T, 3> xzw() const;
            std::array<T, 3> xzy() const;
            std::array<T, 3> xwy() const;
            std::array<T, 3> xwz() const;
            std::array<T, 3> yxz() const;
            std::array<T, 3> yxw() const;
            std::array<T, 3> yzx() const;
            std::array<T, 3> yzw() const;
            std::array<T, 3> ywx() const;
            std::array<T, 3> ywz() const;
            std::array<T, 3> zxy() const;
            std::array<T, 3> zxw() const;
            std::array<T, 3> zyx() const;
            std::array<T, 3> zyw() const;
            std::array<T, 3> zwx() const;
            std::array<T, 3> zwy() const;
            std::array<T, 3> wxy() const;
            std::array<T, 3> wxz() const;
            std::array<T, 3> wyx() const;
            std::array<T, 3> wyz() const;
            std::array<T, 3> wzx() const;
            std::array<T, 3> wzy() const;
            std::array<T, 4> xyzw() const;
            std::array<T, 4> xywz() const;
            std::array<T, 4> xwyz() const;
            std::array<T, 4> xwzy() const;
            std::array<T, 4> xzwy() const;
            std::array<T, 4> xzyw() const;
            std::array<T, 4> yxzw() const;
            std::array<T, 4> yxwz() const;
            std::array<T, 4> yzxw() const;
            std::array<T, 4> yzwx() const;
            std::array<T, 4> ywxz() const;
            std::array<T, 4> ywzx() const;
            std::array<T, 4> zxyw() const;
            std::array<T, 4> zxwy() const;
            std::array<T, 4> zyxw() const;
            std::array<T, 4> zywx() const;
            std::array<T, 4> zwxy() const;
            std::array<T, 4> zwyx() const;
            std::array<T, 4> wxyz() const;
            std::array<T, 4> wxzy() const;
            std::array<T, 4> wyxz() const;
            std::array<T, 4> wyzx() const;
            std::array<T, 4> wzxy() const;
            std::array<T, 4> wzyx() const;

            Vec4<T> &x(const T &value);
            Vec4<T> &y(const T &value);
            Vec4<T> &z(const T &value);
            Vec4<T> &w(const T &value);
            Vec4<T> &xy(const T &first, const T &second);
            Vec4<T> &xz(const T &first, const T &second);
            Vec4<T> &xw(const T &first, const T &second);
            Vec4<T> &yz(const T &first, const T &second);
            Vec4<T> &yw(const T &first, const T &second);
            Vec4<T> &zw(const T &first, const T &second);
            Vec4<T> &yx(const T &first, const T &second);
            Vec4<T> &zx(const T &first, const T &second);
            Vec4<T> &wx(const T &first, const T &second);
            Vec4<T> &zy(const T &first, const T &second);
            Vec4<T> &wy(const T &first, const T &second);
            Vec4<T> &wz(const T &first, const T &second);
            Vec4<T> &xyz(const T &first, const T &second, const T &third);
            Vec4<T> &xyw(const T &first, const T &second, const T &third);
            Vec4<T> &xzw(const T &first, const T &second, const T &third);
            Vec4<T> &xzy(const T &first, const T &second, const T &third);
            Vec4<T> &xwy(const T &first, const T &second, const T &third);
            Vec4<T> &xwz(const T &first, const T &second, const T &third);
            Vec4<T> &yxz(const T &first, const T &second, const T &third);
            Vec4<T> &yxw(const T &first, const T &second, const T &third);
            Vec4<T> &yzx(const T &first, const T &second, const T &third);
            Vec4<T> &yzw(const T &first, const T &second, const T &third);
            Vec4<T> &ywx(const T &first, const T &second, const T &third);
            Vec4<T> &ywz(const T &first, const T &second, const T &third);
            Vec4<T> &zxy(const T &first, const T &second, const T &third);
            Vec4<T> &zxw(const T &first, const T &second, const T &third);
            Vec4<T> &zyx(const T &first, const T &second, const T &third);
            Vec4<T> &zyw(const T &first, const T &second, const T &third);
            Vec4<T> &zwx(const T &first, const T &second, const T &third);
            Vec4<T> &zwy(const T &first, const T &second, const T &third);
            Vec4<T> &wxy(const T &first, const T &second, const T &third);
            Vec4<T> &wxz(const T &first, const T &second, const T &third);
            Vec4<T> &wyx(const T &first, const T &second, const T &third);
            Vec4<T> &wyz(const T &first, const T &second, const T &third);
            Vec4<T> &wzx(const T &first, const T &second, const T &third);
            Vec4<T> &wzy(const T &first, const T &second, const T &third);
            Vec4<T> &xyzw(const T &first, const T &second, const T &third, const T &fourth);
            Vec4<T> &xywz(const T &first, const T &second, const T &third, const T &fourth);
            Vec4<T> &xwyz(const T &first, const T &second, const T &third, const T &fourth);
            Vec4<T> &xwzy(const T &first, const T &second, const T &third, const T &fourth);
            Vec4<T> &xzwy(const T &first, const T &second, const T &third, const T &fourth);
            Vec4<T> &xzyw(const T &first, const T &second, const T &third, const T &fourth);
            Vec4<T> &yxzw(const T &first, const T &second, const T &third, const T &fourth);
            Vec4<T> &yxwz(const T &first, const T &second, const T &third, const T &fourth);
            Vec4<T> &yzxw(const T &first, const T &second, const T &third, const T &fourth);
            Vec4<T> &yzwx(const T &first, const T &second, const T &third, const T &fourth);
            Vec4<T> &ywxz(const T &first, const T &second, const T &third, const T &fourth);
            Vec4<T> &ywzx(const T &first, const T &second, const T &third, const T &fourth);
            Vec4<T> &zxyw(const T &first, const T &second, const T &third, const T &fourth);
            Vec4<T> &zxwy(const T &first, const T &second, const T &third, const T &fourth);
            Vec4<T> &zyxw(const T &first, const T &second, const T &third, const T &fourth);
            Vec4<T> &zywx(const T &first, const T &second, const T &third, const T &fourth);
            Vec4<T> &zwxy(const T &first, const T &second, const T &third, const T &fourth);
            Vec4<T> &zwyx(const T &first, const T &second, const T &third, const T &fourth);
            Vec4<T> &wxyz(const T &first, const T &second, const T &third, const T &fourth);
            Vec4<T> &wxzy(const T &first, const T &second, const T &third, const T &fourth);
            Vec4<T> &wyxz(const T &first, const T &second, const T &third, const T &fourth);
            Vec4<T> &wyzx(const T &first, const T &second, const T &third, const T &fourth);
            Vec4<T> &wzxy(const T &first, const T &second, const T &third, const T &fourth);
            Vec4<T> &wzyx(const T &first, const T &second, const T &third, const T &fourth);
            
            Vec4<T> &xy(const std::array<T, 2> &value);
            Vec4<T> &xz(const std::array<T, 2> &value);
            Vec4<T> &xw(const std::array<T, 2> &value);
            Vec4<T> &yz(const std::array<T, 2> &value);
            Vec4<T> &yw(const std::array<T, 2> &value);
            Vec4<T> &zw(const std::array<T, 2> &value);
            Vec4<T> &yx(const std::array<T, 2> &value);
            Vec4<T> &zx(const std::array<T, 2> &value);
            Vec4<T> &wx(const std::array<T, 2> &value);
            Vec4<T> &zy(const std::array<T, 2> &value);
            Vec4<T> &wy(const std::array<T, 2> &value);
            Vec4<T> &wz(const std::array<T, 2> &value);
            Vec4<T> &xyz(const std::array<T, 3> &value);
            Vec4<T> &xyw(const std::array<T, 3> &value);
            Vec4<T> &xzw(const std::array<T, 3> &value);
            Vec4<T> &xzy(const std::array<T, 3> &value);
            Vec4<T> &xwy(const std::array<T, 3> &value);
            Vec4<T> &xwz(const std::array<T, 3> &value);
            Vec4<T> &yxz(const std::array<T, 3> &value);
            Vec4<T> &yxw(const std::array<T, 3> &value);
            Vec4<T> &yzx(const std::array<T, 3> &value);
            Vec4<T> &yzw(const std::array<T, 3> &value);
            Vec4<T> &ywx(const std::array<T, 3> &value);
            Vec4<T> &ywz(const std::array<T, 3> &value);
            Vec4<T> &zxy(const std::array<T, 3> &value);
            Vec4<T> &zxw(const std::array<T, 3> &value);
            Vec4<T> &zyx(const std::array<T, 3> &value);
            Vec4<T> &zyw(const std::array<T, 3> &value);
            Vec4<T> &zwx(const std::array<T, 3> &value);
            Vec4<T> &zwy(const std::array<T, 3> &value);
            Vec4<T> &wxy(const std::array<T, 3> &value);
            Vec4<T> &wxz(const std::array<T, 3> &value);
            Vec4<T> &wyx(const std::array<T, 3> &value);
            Vec4<T> &wyz(const std::array<T, 3> &value);
            Vec4<T> &wzx(const std::array<T, 3> &value);
            Vec4<T> &wzy(const std::array<T, 3> &value);
            Vec4<T> &xyzw(const std::array<T, 4> &value);
            Vec4<T> &xywz(const std::array<T, 4> &value);
            Vec4<T> &xwyz(const std::array<T, 4> &value);
            Vec4<T> &xwzy(const std::array<T, 4> &value);
            Vec4<T> &xzwy(const std::array<T, 4> &value);
            Vec4<T> &xzyw(const std::array<T, 4> &value);
            Vec4<T> &yxzw(const std::array<T, 4> &value);
            Vec4<T> &yxwz(const std::array<T, 4> &value);
            Vec4<T> &yzxw(const std::array<T, 4> &value);
            Vec4<T> &yzwx(const std::array<T, 4> &value);
            Vec4<T> &ywxz(const std::array<T, 4> &value);
            Vec4<T> &ywzx(const std::array<T, 4> &value);
            Vec4<T> &zxyw(const std::array<T, 4> &value);
            Vec4<T> &zxwy(const std::array<T, 4> &value);
            Vec4<T> &zyxw(const std::array<T, 4> &value);
            Vec4<T> &zywx(const std::array<T, 4> &value);
            Vec4<T> &zwxy(const std::array<T, 4> &value);
            Vec4<T> &zwyx(const std::array<T, 4> &value);
            Vec4<T> &wxyz(const std::array<T, 4> &value);
            Vec4<T> &wxzy(const std::array<T, 4> &value);
            Vec4<T> &wyxz(const std::array<T, 4> &value);
            Vec4<T> &wyzx(const std::array<T, 4> &value);
            Vec4<T> &wzxy(const std::array<T, 4> &value);
            Vec4<T> &wzyx(const std::array<T, 4> &value);
    };

    template class Vec4<float>;
    template class Vec4<double>;
    template class Vec4<char>;
    template class Vec4<short>;
    template class Vec4<int>;
    template class Vec4<unsigned char>;
    template class Vec4<unsigned short>;
    template class Vec4<unsigned int>;
}
